In [1]:
import numpy as np
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
print(type(a)) # >>><class 'numpy.ndarray'>
print(a.dtype) 
print(a.size) # >>>25
print(a.shape) # >>>(5, 5)

<class 'numpy.ndarray'>
int32
25
(5, 5)


In [2]:
print(a[0, 1:4]) # >>>[12 13 14]
print(a[1:4, 0]) # >>>[16 21 26]
print(a[::2,::2]) # >>>[[11 13 15]
                  #     [21 23 25]
                  #     [31 33 35]]
print(a[:, 1]) # >>>[12 17 22 27 32]

[12 13 14]
[16 21 26]
[[11 13 15]
 [21 23 25]
 [31 33 35]]
[12 17 22 27 32]


In [3]:
import pandas as pd
import numpy as np
#如何从列表，数组，字典构建series
mylist = list('abcedfghijklmnopqrstuvwxyz')   # 列表
myarr = np.arange(26)                          # 数组
mydict = dict(zip(mylist, myarr))             # 字典

# 构建方法
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser3.head())                 # 打印前5个数据

a    0
b    1
c    2
e    3
d    4
dtype: int64


In [4]:
# series转换为dataframe
df = ser1.to_frame()
# 索引列转换为dataframe的列
df.reset_index(inplace=True)
print(df.head())

   index  0
0      0  a
1      1  b
2      2  c
3      3  e
4      4  d


In [5]:
# 构建series1
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz')) 
# 构建series2
ser2 = pd.Series(np.arange(26))

# 方法1，axis=1表示列拼接，0表示行拼接
#df = pd.concat([ser1, ser2], axis=1)
#df
#type(df)
# 与方法1相比，方法2设置了列名
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())
type(df)

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


pandas.core.frame.DataFrame

In [6]:
#如何命名列索引的名称

ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

# 命名索引列名称
ser.name = 'alphabets'
# 显示前5行数据
ser.head()



0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [7]:
#如何获得series对象A中不包含series对象B的元素
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# 返回ser1不包含ser2的布尔型series
ser3=~ser1.isin(ser2)
# 获取ser不包含ser2的元素
ser1[ser3]

0    1
1    2
2    3
dtype: int64

In [8]:
#如何获得seriesA和seriesB不相同的项

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# 求ser1和ser2的并集
ser_u = pd.Series(np.union1d(ser1, ser2))
# 求ser1和ser2的交集
ser_i = pd.Series(np.intersect1d(ser1, ser2))
# ser_i在ser_u的补集就是ser1和ser2不相同的项
ser_u[~ser_u.isin(ser_i)]


0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [9]:
#如何获得数值series的四分位值

# 设置随机数种子
state = np.random.RandomState(100)
# 从均值为5标准差为25的正态分布随机抽取5个点构成series
ser = pd.Series(state.normal(10, 5, 25))
# 求ser的四分位数
np.percentile(ser, q=[0, 25, 50, 75, 100])


array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

In [10]:
#如何获得series中单一项的频率计数
#从0~7随机抽取30个列表值，组成series
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
# 对该series进行计数
ser.value_counts()

g    7
c    5
f    5
d    5
e    5
a    2
b    1
dtype: int64

In [11]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [12]:
from sklearn.datasets import load_iris
iris_data = load_iris()
type(iris_data.data)

numpy.ndarray