In [9]:
#决策树
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, plot_tree

# Load data
iris = load_iris()

#划分训练集和测试集
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

#训练，预测
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
predict_target=clf.predict(x_test)

#预测结果与真实结果的对比
print(sum(predict_target==y_test))

#输出准确率，召回率，F值
print(metrics.classification_report(y_test,predict_target))
print(metrics.confusion_matrix(y_test, predict_target))

42
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.92      0.85      0.88        13
           2       0.89      0.94      0.91        17

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

[[15  0  0]
 [ 0 11  2]
 [ 0  1 16]]


In [22]:
#决策树
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import datasets, ensemble

# Load data
iris = load_iris()

#划分训练集和测试集
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

#训练，预测
clf = ensemble.RandomForestClassifier(max_depth=3, n_estimators=5, max_features=3)
clf.fit(x_train,y_train)
predict_target=clf.predict(x_test)

#预测结果与真实结果的对比
print(sum(predict_target==y_test))

#输出准确率，召回率，F值
print(metrics.classification_report(y_test,predict_target))

44
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        12

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

